[2024-11-25T05:38:00.201+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T05:38:00.229+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_history_reports.process_history_reports_task manual__2024-11-25T05:37:45.529743+00:00 [queued]>
[2024-11-25T05:38:00.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_history_reports.process_history_reports_task manual__2024-11-25T05:37:45.529743+00:00 [queued]>
[2024-11-25T05:38:00.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-25T05:38:00.275+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_history_reports_task> on 2024-11-25 05:37:45.529743+00:00
[2024-11-25T05:38:00.312+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6334) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T05:38:00.315+0000] {standard_task_runner.py:72} INFO - Started process 6336 to run task
[2024-11-25T05:38:00.312+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_history_reports', 'process_history_reports_task', 'manual__2024-11-25T05:37:45.529743+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpl6idh6h0']
[2024-11-25T05:38:00.317+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask process_history_reports_task
[2024-11-25T05:38:00.414+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_history_reports.process_history_reports_task manual__2024-11-25T05:37:45.529743+00:00 [running]> on host c38f41c7f3f7
[2024-11-25T05:38:01.061+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_history_reports' AIRFLOW_CTX_TASK_ID='process_history_reports_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T05:37:45.529743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T05:37:45.529743+00:00'
[2024-11-25T05:38:01.064+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T05:38:04.639+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/data_processing/history_reports_processing_script.py:220 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-11-25T05:38:04.946+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/history_reports/disaster_8_1_2024.csv
[2024-11-25T05:38:05.451+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/history_reports/grantee_8_1_2024.csv
[2024-11-25T05:38:05.734+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/history_reports/grant_8_1_2024.csv
[2024-11-25T05:38:06.039+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/history_reports/publiclaw_8_1_2024.csv
[2024-11-25T05:38:06.300+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/history_reports/disaster_publiclaw_8_1_2024.csv
[2024-11-25T05:38:06.684+0000] {logging_mixin.py:190} INFO - File moved from s3://project-raw-data-files/history_reports/CDBG_DR_Grant_History_8_1_2024.pdf to s3://project-raw-data-files/archived/history_reports/CDBG_DR_Grant_History_8_1_2024.pdf
[2024-11-25T05:38:06.688+0000] {logging_mixin.py:190} INFO - Processed file saved to S3: s3://project-processed-data/CDBG_DR_Grant_History_8_1_2024.pdf
[2024-11-25T05:38:06.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-25T05:38:06.710+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T05:38:06.712+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL_history_reports, task_id=process_history_reports_task, run_id=manual__2024-11-25T05:37:45.529743+00:00, execution_date=20241125T053745, start_date=20241125T053800, end_date=20241125T053806
[2024-11-25T05:38:06.785+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-25T05:38:06.809+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T05:38:06.813+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
